<a href="https://colab.research.google.com/github/iamfady/NLP/blob/main/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word Embedding Techniques using Embedding Layer in Keras


In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0

from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=10000

# One Hot Representation


In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[4788, 380, 2119, 3255], [4788, 380, 2119, 6800], [4788, 7607, 2119, 6337], [1049, 3747, 9570, 3184, 5203], [1049, 3747, 9570, 3184, 2120], [7912, 4788, 2973, 2119, 5087], [2153, 333, 5278, 3184]]


# Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4788  380 2119 3255]
 [   0    0    0    0 4788  380 2119 6800]
 [   0    0    0    0 4788 7607 2119 6337]
 [   0    0    0 1049 3747 9570 3184 5203]
 [   0    0    0 1049 3747 9570 3184 2120]
 [   0    0    0 7912 4788 2973 2119 5087]
 [   0    0    0    0 2153  333 5278 3184]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step
[[[ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796
   -0.02987136  0.00328615 -0.03151263  0.0372937  -0.00599752]
  [ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796
   -0.02987136  0.00328615 -0.03151263  0.0372937  -0.00599752]
  [ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796
   -0.02987136  0.00328615 -0.03151263  0.0372937  -0.00599752]
  [ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796
   -0.02987136  0.00328615 -0.03151263  0.0372937  -0.00599752]
  [ 0.04142508 -0.03066613 -0.04993593  0.04076788  0.03461094
   -0.02232511 -0.03868157  0.03594211 -0.0044188  -0.03933664]
  [-0.01908178 -0.02992477 -0.02256122 -0.00642917  0.04136184
    0.00251435 -0.03071213 -0.01479835  0.00962963 -0.04745542]
  [ 0.04497427  0.00732381 -0.04585824  0.03746445 -0.0386049
    0.02357639  0.04060135  0.00776026 -0.00804467 -0.0479996 ]
  [ 0.01079447  0.00928492  0.02405811  0.04499109 -0.0289426
   -0.03880

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 4788,  380, 2119, 3255], dtype=int32)

In [14]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[[ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796 -0.02987136
   0.00328615 -0.03151263  0.0372937  -0.00599752]
 [ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796 -0.02987136
   0.00328615 -0.03151263  0.0372937  -0.00599752]
 [ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796 -0.02987136
   0.00328615 -0.03151263  0.0372937  -0.00599752]
 [ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796 -0.02987136
   0.00328615 -0.03151263  0.0372937  -0.00599752]
 [ 0.04142508 -0.03066613 -0.04993593  0.04076788  0.03461094 -0.02232511
  -0.03868157  0.03594211 -0.0044188  -0.03933664]
 [-0.01908178 -0.02992477 -0.02256122 -0.00642917  0.04136184  0.00251435
  -0.03071213 -0.01479835  0.00962963 -0.04745542]
 [ 0.04497427  0.00732381 -0.04585824  0.03746445 -0.0386049   0.02357639
   0.04060135  0.00776026 -0.00804467 -0.0479996 ]
 [ 0.01079447  0.00928492  0.02405811  0.04499109 -0.0289426  -0.03880855
   0.01768193

In [15]:
print(model.predict(embedded_docs)[1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[[ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796 -0.02987136
   0.00328615 -0.03151263  0.0372937  -0.00599752]
 [ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796 -0.02987136
   0.00328615 -0.03151263  0.0372937  -0.00599752]
 [ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796 -0.02987136
   0.00328615 -0.03151263  0.0372937  -0.00599752]
 [ 0.02642412 -0.02957629 -0.03541461 -0.0393028  -0.04795796 -0.02987136
   0.00328615 -0.03151263  0.0372937  -0.00599752]
 [ 0.04142508 -0.03066613 -0.04993593  0.04076788  0.03461094 -0.02232511
  -0.03868157  0.03594211 -0.0044188  -0.03933664]
 [-0.01908178 -0.02992477 -0.02256122 -0.00642917  0.04136184  0.00251435
  -0.03071213 -0.01479835  0.00962963 -0.04745542]
 [ 0.04497427  0.00732381 -0.04585824  0.03746445 -0.0386049   0.02357639
   0.04060135  0.00776026 -0.00804467 -0.0479996 ]
 [-0.03767524 -0.02778329 -0.03874835 -0.02336698 -0.02475845  0.04697296
  -0.03003726